### PR TITLE
Prompt + app

### PR DESCRIPTION
**Pull request by PortnovaO**
Prompt now has total values
Location request removed 
App temperature increased 
App max tokens changed

### CODE REVIEW

**Review by yotamraz — APPROVED** [review]
LGTM

**Comment by yotamraz** [comment]
approved,
should I deploy?

**Comment by PortnovaO** [comment]
Yes, please

Best regards,
Olga

**Comment by yotamraz** [comment]
Will do in the next hour.

I'll try to add CI/CD with git actions for automatic deployment upon merge
to main.

**Comment by yotamraz** [comment]
new version now deployed

**Pull request merged**
